
class php::params::mysql inherits php::params {

  $package                           = module_param('mysql_package')
  $ensure                            = module_param('mysql_ensure')
  $module_configs                    = module_param('mysql_module_configs')
  $template                          = module_param('mysql_template')

  #---

  $sql_safe_mode                     = module_param('sql_safe_mode')
  $mysqlnd_collect_statistics        = module_param('mysqlnd_collect_statistics')
  $mysqlnd_collect_memory_statistics = module_param('mysqlnd_collect_memory_statistics')
  $mysqlnd_net_cmd_buffer_size       = module_param('mysqlnd_net_cmd_buffer_size')
  $mysqlnd_net_read_buffer_size      = module_param('mysqlnd_net_read_buffer_size')
  $mysql_allow_local_infile          = module_param('mysql_allow_local_infile')
  $mysql_allow_persistent            = module_param('mysql_allow_persistent')
  $mysql_cache_size                  = module_param('mysql_cache_size')
  $mysql_max_persistent              = module_param('mysql_max_persistent')
  $mysql_max_links                   = module_param('mysql_max_links')
  $mysql_default_port                = module_param('mysql_default_port')
  $mysql_default_socket              = module_param('mysql_default_socket')
  $mysql_default_host                = module_param('mysql_default_host')
  $mysql_default_user                = module_param('mysql_default_user')
  $mysql_default_password            = module_param('mysql_default_password')
  $mysql_connect_timeout             = module_param('mysql_connect_timeout')
  $mysql_trace_mode                  = module_param('mysql_trace_mode')
  $mysqli_max_persistent             = module_param('mysqli_max_persistent')
  $mysqli_allow_local_infile         = module_param('mysqli_allow_local_infile')
  $mysqli_allow_persistent           = module_param('mysqli_allow_persistent')
  $mysqli_max_links                  = module_param('mysqli_max_links')
  $mysqli_cache_size                 = module_param('mysqli_cache_size')
  $mysqli_default_port               = module_param('mysqli_default_port')
  $mysqli_default_socket             = module_param('mysqli_default_socket')
  $mysqli_default_host               = module_param('mysqli_default_host')
  $mysqli_default_user               = module_param('mysqli_default_user')
  $mysqli_default_pw                 = module_param('mysqli_default_pw')
  $mysqli_reconnect                  = module_param('mysqli_reconnect')
  $pdo_mysql_cache_size              = module_param('pdo_mysql_cache_size')
  $pdo_mysql_default_socket          = module_param('pdo_mysql_default_socket')
}
